/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-24 00:30:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.foodshop.manager.productProcess;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Timestamp;

public final class foodRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/foodshop/manager/productProcess/../../etc/color.jspf", Long.valueOf(1716509644971L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("java.sql.Timestamp");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String bodyback_c="#e0ffff";
String back_c="#8fbc8f";
String title_c="#5f9ea0";
String value_c="#b0e0e6";
String bar="#778899";

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>상품등록</title>\r\n");
      out.write("<link href=\"../../etc/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../etc/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"");
      out.print(bodyback_c);
      out.write("\">\r\n");
      out.write("<p>음식 등록</p>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" name=\"writeform\" id=\"fileForm\"\r\n");
      out.write("     action=\"foodRegister.do\"  enctype=\"multipart/form-data\">   \r\n");
      out.write("<table>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td align=\"right\" colspan=\"2\" bgcolor=\"");
      out.print(value_c);
      out.write("\">\r\n");
      out.write("	    <a href=\"../managerMain.do\"> 관리자 메인으로</a> \r\n");
      out.write("   </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td  width=\"100\"  bgcolor=\"");
      out.print(value_c);
      out.write("\">분류 선택</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">\r\n");
      out.write("       <select name=\"food_kind\" id=\"foodKind\">\r\n");
      out.write("           <option value=\"100\">한식</option>\r\n");
      out.write("           <option value=\"200\">중식</option>\r\n");
      out.write("           <option value=\"300\">일식</option>\r\n");
      out.write("           <option value=\"400\">양식</option>\r\n");
      out.write("           <option value=\"500\">치킨</option>\r\n");
      out.write("           <option value=\"600\">면</option>\r\n");
      out.write("           <option value=\"700\">만두</option>\r\n");
      out.write("       </select>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td  width=\"100\"  bgcolor=\"");
      out.print(value_c);
      out.write("\">상품 이름</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">\r\n");
      out.write("        <input type=\"text\" size=\"50\" maxlength=\"50\" name=\"food_name\" id=\"foodName\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td  width=\"100\"  bgcolor=\"");
      out.print(value_c);
      out.write("\">가 격</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">\r\n");
      out.write("        <input type=\"text\" size=\"10\" maxlength=\"9\" name=\"food_price\" id=\"foodPrice\">원</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td  width=\"100\"  bgcolor=\"");
      out.print(value_c);
      out.write("\">수량</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">\r\n");
      out.write("        <input type=\"text\" size=\"10\" maxlength=\"5\" name=\"food_count\" id=\"foodCount\">개</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td  width=\"100\"  bgcolor=\"");
      out.print(value_c);
      out.write("\">이미지</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">\r\n");
      out.write("        <input type=\"file\" name=\"food_image\" id=\"foodImage\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("<tr>      \r\n");
      out.write(" <td colspan=2 bgcolor=\"");
      out.print(value_c);
      out.write("\" align=\"center\"> \r\n");
      out.write("  <input type=\"button\" value=\"음식 등록\" onclick=\"checkForm(this.form)\">  \r\n");
      out.write("  <input type=\"reset\" value=\"다시작성\">\r\n");
      out.write("</td></tr></table>   \r\n");
      out.write("   \r\n");
      out.write("</form>      \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
